name: New Content
description: Want to add new content？
title: "[New Content]: " 
body:
- type: markdown
  attributes:
    value: |
      > This repository is for StarRocks DOCS ONLY. If you need assistance on StarRocks usage, [file an issue in StarRocks repository](https://github.com/StarRocks/starrocks/issues/new/choose).
- type: textarea
  attributes:
    label: Describe the Content 
    description: |
      > - Provide details of the content to add, such as feature description, procedure, code, image, term, etc. 
      > - You can also directly contribute the new content to StarRocks DOCS.
  validations:
    required: true
- type: textarea
  attributes:
    label: Additional Info
    description: |
      Any additional information that might help, such as doc link, sketches.
  validations:
    required: false
